[package]
name = "conswol"
version = "0.1.0"
authors = ["Mason Ashbridge <masonjash@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.4.8"
serde = "1.0.79"
serde_derive = "1.0.79"
tui = "0.3.0-beta.3"
termion = "1.5.1"
ctrlc = "3.1.1"
